#!/bin/bash

set -e

work_path=`dirname $0`
work_path=`cd $work_path; pwd`

output=$work_path/Log/`date +"%Y-%m-%d"`.log 

mkdir -p $work_path/Log 

for path in `cat "$work_path"/bin.cfg | grep -v '#'`; do
    bin_name=`basename $path`
    echo "********************************************" >> $output
    echo "Cleaning $bin_name" >> $output
    echo "********************************************" >> $output

    "$work_path"/clean_one_develop $path >> $output 2>>$output
    echo >> $output
done
